baseURL = 'https://bemasher.net/'
languageCode = 'en-us'
title = 'bemasher.net'
theme = 'plain'

enableGitInfo = true

[taxonomies]
  tag = 'tags'

[menus]
[[menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10
