baseURL = 'https://bemasher.net/'
languageCode = 'en-us'
title = 'bemasher.net'
theme = 'plain'

[taxonomies]
  project = 'projects'
  tag = 'tags'

[menus]
[[menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10
[[menus.main]]
  name = 'Projects'
  pageRef = '/projects'
  weight = 20
